### ISSUE TITLE
Gulp recompile failing silently

### ISSUE THREAD

**Issue by edge0701** [shamadee/wasm-init#15]
wasm-compile is returning a status code of 0, even for failed compilation, meaning that the gulp recompile process is failing silently.

**Comment by matzewagner** [comment]
What operating system and Node version are you running on? Thanks!

**Comment by matzewagner** [comment]
Latest commit should solve this.

**Comment by edge0701** [comment]
Nice work. Almost there.
The `if (stderr)` clause works, but it still needs to call the callback (with, for instance, `cb(true)`) so that the gulp process can continue. So when we correct the error, gulp will try and recompile again. Otherwise it just halts gulp completely.

**Comment by matzewagner** [comment]
Ok, I'm seeing that I will need to rethink the compile process with gulp a little. For now, I issued another commit, which should fix this. Thanks for your advice!
